---
title: 'Developing Data Products Week 3: Cars'
author: "Miguel Adarlo"
date: "2023-08-09"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Finding the Miles per Gallon of Cars

- Mtcars is a dataset from the 1974 Motor Trend US Magazine.
- Comprises of fuel consumption and aspects of automobile design and performance for 32 cars made from 1973 to 1974.
- Goal of this presentation: Show how the Miles per Gallon of a car is related to its horsepower, among other predictors

## Miles per Gallon Plot

``` {r loading libraries, message = FALSE}
library(plotly)
```

``` {r plotting}
plot_ly(data = mtcars, x = ~hp, y = ~mpg, 
        color = ~as.factor(cyl), size = ~wt,
        text = ~paste("Horsepower: ", hp, '<br>Miles per Gallon:', mpg),
        type = "scatter", mode = "markers") %>%
  layout(legend=(list(title=list(text="<b>Number of Cylinders<b>"))), title = "Miles per Gallon: Miles per Gallon by Horsepower")
```

